package com.example.demo.mock;

import com.example.demo.user.domain.User;
import com.example.demo.user.domain.UserStatus;
import com.example.demo.user.service.port.UserRepository;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class FakeUserRepository implements UserRepository {

    private long autoGeneratedId = 0L;
    private final List<User> data = new ArrayList<>();

    @Override
    public Optional<User> findByEmailAndStatus(String email, UserStatus userStatus) {
        return data.stream()
                .filter(user -> user.getEmail().equals(email))
                .filter(user -> user.getStatus().equals(userStatus))
                .findAny();
    }

    @Override
    public Optional<User> findByIdAndStatus(long id, UserStatus userStatus) {
        return data.stream()
                .filter(user -> user.getId().equals(id))
                .filter(user -> user.getStatus().equals(userStatus))
                .findAny();
    }

    @Override
    public User save(User user) {
        if (user.getId() == null|| user.getId() == 0) {
            user = User.builder()
                    .id(++autoGeneratedId)
                    .address(user.getAddress())
                    .email(user.getEmail())
                    .nickname(user.getNickname())
                    .status(user.getStatus())
                    .certificationCode(user.getCertificationCode())
                    .lastLoginAt(user.getLastLoginAt())
                    .build();
        }else{
            // 이미 있는 경우
            User finalUser = user;
            data.removeIf(u -> u.getId().equals(finalUser.getId()));
        }
        data.add(user);
        return user;
    }

    @Override
    public Optional<User> findById(long id) {
        return data.stream().filter(user -> user.getId().equals(id)).findAny();
    }
}
